// AUTO-GENERATED from 2023.xlsx "Master List" (426 institutions). Do not edit by hand.
// Source columns: CERT, NAME, CITY, STATE, PFR (regulator), ASSETS ($000), HOLDING COMPANY.

export type SeedBank = {
  cert: number | null;
  name: string;
  city: string | null;
  state: string | null;
  regulator: string | null;
  assets: number | null;
  holding_company: string | null;
};

export const BANKS_SEED: SeedBank[] = [
  { cert: 12013, name: "Union County Savings Bank", city: "ELIZABETH", state: "NJ", regulator: "FDIC", assets: 1820867, holding_company: null },
  { cert: 13063, name: "Kennebunk Savings Bank", city: "KENNEBUNK", state: "ME", regulator: "FDIC", assets: 1846791, holding_company: "KENNEBUNK SAVINGS BANCORP, MHC" },
  { cert: 14134, name: "Passumpsic Savings Bank", city: "ST. JOHNSBURY", state: "VT", regulator: "FDIC", assets: 838127, holding_company: "PASSUMPSIC BANCORP" },
  { cert: 14136, name: "Wells River Savings Bank", city: "WELLS RIVER", state: "VT", regulator: "FDIC", assets: 228201, holding_company: null },
  { cert: 14140, name: "Northfield Savings Bank", city: "NORTHFIELD", state: "VT", regulator: "FDIC", assets: 1414255, holding_company: "NORTHFIELD MHC" },
  { cert: 15912, name: "Savings Bank of Danbury", city: "DANBURY", state: "CT", regulator: "FDIC", assets: 1438145, holding_company: "SBD BANCORP, INC." },
  { cert: 15966, name: "Fulton Savings Bank", city: "FULTON", state: "NY", regulator: "FDIC", assets: 475722, holding_company: null },
  { cert: 15969, name: "Rondout Savings Bank", city: "KINGSTON", state: "NY", regulator: "FDIC", assets: 524847, holding_company: null },
  { cert: 15970, name: "Ulster Savings Bank", city: "KINGSTON", state: "NY", regulator: "FDIC", assets: 1247761, holding_company: null },
  { cert: 15987, name: "Walden Savings Bank", city: "MONTGOMERY", state: "NY", regulator: "OCC", assets: 736016, holding_company: null },
  { cert: 15990, name: "Watertown Savings Bank", city: "WATERTOWN", state: "NY", regulator: "FDIC", assets: 923496, holding_company: null },
  { cert: 16026, name: "Ridgewood Savings Bank", city: "RIDGEWOOD", state: "NY", regulator: "FDIC", assets: 6834299, holding_company: null },
  { cert: 16030, name: "The North Country Savings Bank", city: "CANTON", state: "NY", regulator: "FDIC", assets: 308828, holding_company: null },
  { cert: 16032, name: "Rhinebeck Bank", city: "RHINEBECK", state: "NY", regulator: "FDIC", assets: 1335810, holding_company: "RHINEBECK BANCORP, MHC" },
  { cert: 16039, name: "Sawyer Savings Bank", city: "SAUGERTIES", state: "NY", regulator: "FDIC", assets: 277985, holding_company: null },
  { cert: 16101, name: "The Milford Bank", city: "MILFORD", state: "CT", regulator: "FDIC", assets: 559839, holding_company: null },
  { cert: 16636, name: "The Torrington Savings Bank", city: "TORRINGTON", state: "CT", regulator: "FDIC", assets: 908945, holding_company: null },
  { cert: 17115, name: "Partners Bank of New England", city: "SANFORD", state: "ME", regulator: "FDIC", assets: 1004795, holding_company: "SIS BANCORP, MHC" },
  { cert: 17123, name: "Artisans' Bank", city: "WILMINGTON", state: "DE", regulator: "FDIC", assets: 662318, holding_company: null },
  { cert: 17180, name: "Meredith Village Savings Bank", city: "MEREDITH", state: "NH", regulator: "FDIC", assets: 1552881, holding_company: "NEW HAMPSHIRE MUTUAL BANCORP" },
  { cert: 17262, name: "Essex Savings Bank", city: "ESSEX", state: "CT", regulator: "FDIC", assets: 528294, holding_company: null },
  { cert: 17443, name: "Piscataqua Savings Bank", city: "PORTSMOUTH", state: "NH", regulator: "FDIC", assets: 380965, holding_company: null },
  { cert: 17658, name: "Norway Savings Bank", city: "NORWAY", state: "ME", regulator: "FDIC", assets: 1795136, holding_company: "NORWAY BANCORP, MHC" },
  { cert: 17736, name: "The Hometown Savings Bank", city: "TERRE HAUTE", state: "IN", regulator: "FDIC", assets: 497776, holding_company: "TERRE HAUTE SAVINGS MHC, INC." },
  { cert: 17741, name: "Maine Community Bank", city: "BIDDEFORD", state: "ME", regulator: "FDIC", assets: 1004289, holding_company: "MAINE COMMUNITY BANCORP, MHC" },
  { cert: 17743, name: "Saco & Biddeford Savings Institution", city: "SACO", state: "ME", regulator: "FDIC", assets: 1276362, holding_company: null },
  { cert: 17748, name: "Gorham Savings Bank", city: "GORHAM", state: "ME", regulator: "FDIC", assets: 1607984, holding_company: "GORHAM BANCORP, MHC" },
  { cert: 17749, name: "Bath Savings Institution", city: "BATH", state: "ME", regulator: "FDIC", assets: 1276951, holding_company: null },
  { cert: 17751, name: "Androscoggin Savings Bank", city: "LEWISTON", state: "ME", regulator: "FDIC", assets: 1450036, holding_company: "ANDROSCOGGIN BANCORP, MHC" },
  { cert: 17764, name: "Centreville Bank", city: "WEST WARWICK", state: "RI", regulator: "FDIC", assets: 2127985, holding_company: null },
  { cert: 17797, name: "Rollstone Bank & Trust", city: "FITCHBURG", state: "MA", regulator: "OCC", assets: 792319, holding_company: "ROLLSTONE BANCORP, MHC" },
  { cert: 17870, name: "Cambridge Savings Bank", city: "CAMBRIDGE", state: "MA", regulator: "FDIC", assets: 6474352, holding_company: "CAMBRIDGE FINANCIAL GROUP, INC." },
  { cert: 17897, name: "Kennebec Savings Bank", city: "AUGUSTA", state: "ME", regulator: "FDIC", assets: 1640422, holding_company: "KENNEBEC SAVINGS, MHC" },
  { cert: 17943, name: "Liberty Bank", city: "MIDDLETOWN", state: "CT", regulator: "FDIC", assets: 6944336, holding_company: null },
  { cert: 17951, name: "Franklin Savings Bank", city: "FRANKLIN", state: "NH", regulator: "FDIC", assets: 761892, holding_company: "FRANKLIN BANCORP MHC" },
  { cert: 17960, name: "Merrimack County Savings Bank", city: "CONCORD", state: "NH", regulator: "FDIC", assets: 1317746, holding_company: "NEW HAMPSHIRE MUTUAL BANCORP" },
  { cert: 18012, name: "Bank of New Hampshire", city: "LACONIA", state: "NH", regulator: "FED", assets: 2428150, holding_company: "BNH FINANCIAL" },
  { cert: 18013, name: "Mascoma Bank", city: "LEBANON", state: "NH", regulator: "FED", assets: 2733504, holding_company: "MASCOMA MUTUAL FINANCIAL SERVICES CORPORATION" },
  { cert: 18028, name: "Sugar River Bank", city: "NEWPORT", state: "NH", regulator: "FDIC", assets: 382131, holding_company: "SUGAR RIVER BANCORP MHC" },
  { cert: 18030, name: "Savings Bank of Walpole", city: "WALPOLE", state: "NH", regulator: "FDIC", assets: 702716, holding_company: "NEW HAMPSHIRE MUTUAL BANCORP" },
  { cert: 18038, name: "Claremont Savings Bank", city: "CLAREMONT", state: "NH", regulator: "FDIC", assets: 530906, holding_company: null },
  { cert: 18129, name: "BankNewport", city: "MIDDLETOWN", state: "RI", regulator: "FED", assets: 2508364, holding_company: "OCEANPOINT FINANCIAL PARTNERS, MHC" },
  { cert: 18190, name: "Union Savings Bank", city: "DANBURY", state: "CT", regulator: "FDIC", assets: 2985601, holding_company: "USB BANCORP, INC." },
  { cert: 18194, name: "The Guilford Savings Bank", city: "GUILFORD", state: "CT", regulator: "FDIC", assets: 1048056, holding_company: "GSB MUTUAL HOLDING COMPANY" },
  { cert: 18198, name: "Ion Bank", city: "NAUGATUCK", state: "CT", regulator: "FDIC", assets: 2071879, holding_company: "ION FINANCIAL MHC" },
  { cert: 18199, name: "Newtown Savings Bank", city: "NEWTOWN", state: "CT", regulator: "FDIC", assets: 1846410, holding_company: "NSB MUTUAL HOLDING COMPANY" },
  { cert: 18200, name: "Dime Bank", city: "NORWICH", state: "CT", regulator: "FDIC", assets: 1108849, holding_company: null },
  { cert: 18204, name: "First County Bank", city: "STAMFORD", state: "CT", regulator: "FDIC", assets: 2076907, holding_company: null },
  { cert: 18213, name: "Fairfield County Bank", city: "RIDGEFIELD", state: "CT", regulator: "FDIC", assets: 1919285, holding_company: "FAIRFIELD COUNTY BANK, MHC" },
  { cert: 18227, name: "Stafford Savings Bank", city: "STAFFORD SPRINGS", state: "CT", regulator: "FDIC", assets: 388705, holding_company: null },
  { cert: 18229, name: "Northwest Community Bank", city: "WINSTED", state: "CT", regulator: "FDIC", assets: 1094062, holding_company: "CONNECTICUT MUTUAL HOLDING COMPANY" },
  { cert: 18237, name: "Jewett City Savings Bank", city: "JEWETT CITY", state: "CT", regulator: "FDIC", assets: 403286, holding_company: null },
  { cert: 18238, name: "Chelsea Groton Bank", city: "NORWICH", state: "CT", regulator: "FDIC", assets: 1572496, holding_company: null },
  { cert: 18258, name: "Thomaston Savings Bank", city: "THOMASTON", state: "CT", regulator: "FDIC", assets: 1623924, holding_company: null },
  { cert: 18408, name: "Bangor Savings Bank", city: "BANGOR", state: "ME", regulator: "FDIC", assets: 7377141, holding_company: "BANGOR BANCORP, MHC" },
  { cert: 19525, name: "Mt. McKinley Bank", city: "FAIRBANKS", state: "AK", regulator: "FDIC", assets: 657243, holding_company: null },
  { cert: 19531, name: "Machias Savings Bank", city: "MACHIAS", state: "ME", regulator: "FDIC", assets: 2360784, holding_company: "MACHIAS BANCORP, MHC" },
  { cert: 19532, name: "Skowhegan Savings Bank", city: "SKOWHEGAN", state: "ME", regulator: "FDIC", assets: 774585, holding_company: null },
  { cert: 19836, name: "Franklin Savings Bank", city: "FARMINGTON", state: "ME", regulator: "FED", assets: 578817, holding_company: "FSB BANCORP, MHC" },
  { cert: 20741, name: "Pioneer Bank", city: "ALBANY", state: "NY", regulator: "FDIC", assets: 1834148, holding_company: "PIONEER BANCORP MHC" },
  { cert: 21591, name: "The Bank of Greene County", city: "CATSKILL", state: "NY", regulator: "OCC", assets: 1860315, holding_company: "GREENE COUNTY BANCORP, MHC" },
  { cert: 23286, name: "Fall River Five Cents Savings Bank", city: "FALL RIVER", state: "MA", regulator: "FED", assets: 1705192, holding_company: "BANKFIVE, MHC" },
  { cert: 23287, name: "The Cape Cod Five Cents Savings Bank", city: "ORLEANS", state: "MA", regulator: "FDIC", assets: 5272127, holding_company: "CAPE COD FIVE MUTUAL COMPANY" },
  { cert: 23293, name: "Florence Bank", city: "FLORENCE", state: "MA", regulator: "FDIC", assets: 1864517, holding_company: "FLORENCE BANCORP, MHC" },
  { cert: 23296, name: "Salem Five Cents Savings Bank", city: "SALEM", state: "MA", regulator: "FDIC", assets: 6619741, holding_company: "SALEM FIVE BANCORP" },
  { cert: 23298, name: "Watertown Savings Bank", city: "WATERTOWN", state: "MA", regulator: "FED", assets: 1448597, holding_company: null },
  { cert: 23620, name: "Dedham Institution for Savings", city: "DEDHAM", state: "MA", regulator: "FDIC", assets: 2099129, holding_company: "1831 BANCORP MHC" },
  { cert: 23622, name: "Bristol County Savings Bank", city: "TAUNTON", state: "MA", regulator: "FDIC", assets: 3093991, holding_company: "BEACON BANCORP" },
  { cert: 23992, name: "Country Bank for Savings", city: "WARE", state: "MA", regulator: "FDIC", assets: 1659376, holding_company: null },
  { cert: 26336, name: "The Village Bank", city: "AUBURNDALE", state: "MA", regulator: "FDIC", assets: 1866085, holding_company: null },
  { cert: 26393, name: "The Pittsfield Co-operative Bank", city: "PITTSFIELD", state: "MA", regulator: "FDIC", assets: 391780, holding_company: null },
  { cert: 26395, name: "MutualOne Bank", city: "FRAMINGHAM", state: "MA", regulator: "FDIC", assets: 1214701, holding_company: null },
  { cert: 26397, name: "Greenfield Co-operative Bank", city: "GREENFIELD", state: "MA", regulator: "FED", assets: 765250, holding_company: "GREENFIELD BANCORP MHC" },
  { cert: 26411, name: "Haverhill Bank", city: "HAVERHILL", state: "MA", regulator: "FDIC", assets: 557992, holding_company: "HB HOLDINGS MHC" },
  { cert: 26450, name: "Canton Co-operative Bank", city: "CANTON", state: "MA", regulator: "FED", assets: 153836, holding_company: null },
  { cert: 26451, name: "Fidelity Co-operative Bank", city: "LEOMINSTER", state: "MA", regulator: "FDIC", assets: 1392664, holding_company: "FIDELITY MUTUAL HOLDING COMPANY" },
  { cert: 26455, name: "Savers Co-operative Bank", city: "SOUTHBRIDGE", state: "MA", regulator: "FDIC", assets: 689291, holding_company: null },
  { cert: 26483, name: "Needham Bank", city: "NEEDHAM", state: "MA", regulator: "FED", assets: 3592881, holding_company: "NB FINANCIAL MHC" },
  { cert: 26484, name: "North Shore Bank, a Co-operative Bank", city: "PEABODY", state: "MA", regulator: "FDIC", assets: 1616227, holding_company: "NORTH SHORE BANCORP" },
  { cert: 26487, name: "Walpole Co-operative Bank", city: "WALPOLE", state: "MA", regulator: "FED", assets: 567527, holding_company: null },
  { cert: 26512, name: "Methuen Co-operative Bank", city: "METHUEN", state: "MA", regulator: "FDIC", assets: 126126, holding_company: null },
  { cert: 26513, name: "Stoughton Co-operative Bank", city: "STOUGHTON", state: "MA", regulator: "FED", assets: 118073, holding_company: null },
  { cert: 26516, name: "Wakefield Co-operative Bank", city: "WAKEFIELD", state: "MA", regulator: "FDIC", assets: 300926, holding_company: null },
  { cert: 26517, name: "Cape Cod Co-operative Bank", city: "YARMOUTH PORT", state: "MA", regulator: "FDIC", assets: 1465307, holding_company: "COASTAL AFFILIATES, MHC" },
  { cert: 26523, name: "Hometown Bank", city: "OXFORD", state: "MA", regulator: "FED", assets: 1350307, holding_company: "HOMETOWN FINANCIAL GROUP MHC" },
  { cert: 26536, name: "BankGloucester", city: "GLOUCESTER", state: "MA", regulator: "FDIC", assets: 359522, holding_company: null },
  { cert: 26554, name: "Bank of Easton", city: "NORTH EASTON", state: "MA", regulator: "FED", assets: 186150, holding_company: null },
  { cert: 26555, name: "OneLocal Bank", city: "NORWOOD", state: "MA", regulator: "FDIC", assets: 860247, holding_company: "1889 BANCORP MHC" },
  { cert: 26559, name: "StonehamBank,  A Co-operative Bank", city: "STONEHAM", state: "MA", regulator: "FDIC", assets: 722191, holding_company: null },
  { cert: 26567, name: "North Cambridge Co-operative Bank", city: "CAMBRIDGE", state: "MA", regulator: "FDIC", assets: 88912, holding_company: null },
  { cert: 26576, name: "Wrentham Co-operative Bank", city: "WRENTHAM", state: "MA", regulator: "FDIC", assets: 154430, holding_company: null },
  { cert: 26590, name: "Abington Bank", city: "COHASSET", state: "MA", regulator: "FED", assets: 1354850, holding_company: "HOMETOWN FINANCIAL GROUP MHC" },
  { cert: 26591, name: "Coastal Heritage Bank", city: "WEYMOUTH", state: "MA", regulator: "FED", assets: 932279, holding_company: "EQUITABLE BANCORP, MHC" },
  { cert: 26602, name: "Charles River Bank", city: "MEDWAY", state: "MA", regulator: "FED", assets: 307961, holding_company: "CHARLES RIVER BANCORP, MHC" },
  { cert: 26620, name: "Reading Co-operative Bank", city: "READING", state: "MA", regulator: "FED", assets: 795668, holding_company: null },
  { cert: 26634, name: "Mechanics Cooperative Bank", city: "TAUNTON", state: "MA", regulator: "FDIC", assets: 639977, holding_company: "MECHANICS BANCORP, MHC" },
  { cert: 26922, name: "The Cooperative Bank", city: "ROSLINDALE", state: "MA", regulator: "FDIC", assets: 560585, holding_company: null },
  { cert: 27238, name: "Winchester Co-operative Bank", city: "WINCHESTER", state: "MA", regulator: "FDIC", assets: 773352, holding_company: null },
  { cert: 27269, name: "Dean Co-operative Bank", city: "FRANKLIN", state: "MA", regulator: "FDIC", assets: 439231, holding_company: null },
  { cert: 27385, name: "Port Richmond Savings", city: "PHILADELPHIA", state: "PA", regulator: "FDIC", assets: 103572, holding_company: null },
  { cert: 27567, name: "The Glen Burnie Mutual Savings Bank", city: "GLEN BURNIE", state: "MD", regulator: "FDIC", assets: 109576, holding_company: null },
  { cert: 27619, name: "Piedmont Federal Savings Bank", city: "WINSTON SALEM", state: "NC", regulator: "OCC", assets: 918090, holding_company: "PIEDMONT FINANCIAL HOLDING COMPANY" },
  { cert: 27643, name: "First Federal Bank of Ohio", city: "GALION", state: "OH", regulator: "OCC", assets: 259330, holding_company: null },
  { cert: 27664, name: "Sterling Federal Bank, F.S.B.", city: "STERLING", state: "IL", regulator: "OCC", assets: 487362, holding_company: null },
  { cert: 27678, name: "First Federal Community Bank, SSB", city: "PARIS", state: "TX", regulator: "FDIC", assets: 536877, holding_company: null },
  { cert: 27686, name: "Slovenian Savings and Loan Association of Canonsburg", city: "STRABANE", state: "PA", regulator: "FDIC", assets: 577080, holding_company: null },
  { cert: 27697, name: "Fifth District Savings Bank", city: "NEW ORLEANS", state: "LA", regulator: "OCC", assets: 452796, holding_company: null },
  { cert: 27704, name: "Wake Forest Federal Savings and Loan Association", city: "WAKE FOREST", state: "NC", regulator: "OCC", assets: 108816, holding_company: "WAKE FOREST BANCORP, M.H.C." },
  { cert: 27711, name: "Altoona First Savings Bank", city: "ALTOONA", state: "PA", regulator: "FDIC", assets: 323074, holding_company: null },
  { cert: 27716, name: "Mutual Savings and Loan Association", city: "METAIRIE", state: "LA", regulator: "OCC", assets: 44404, holding_company: null },
  { cert: 27723, name: "Security Bank, s.b.", city: "SPRINGFIELD", state: "IL", regulator: "FDIC", assets: 221589, holding_company: null },
  { cert: 27727, name: "Lyons Federal Bank", city: "LYONS", state: "KS", regulator: "OCC", assets: 148350, holding_company: null },
  { cert: 27752, name: "Hibernia Bank", city: "NEW ORLEANS", state: "LA", regulator: "FDIC", assets: 258851, holding_company: null },
  { cert: 27763, name: "InFirst Bank", city: "INDIANA", state: "PA", regulator: "FDIC", assets: 506725, holding_company: "INFIRST BANCORP, MHC" },
  { cert: 27767, name: "Union Federal Savings and Loan Association", city: "KEWANEE", state: "IL", regulator: "OCC", assets: 161138, holding_company: null },
  { cert: 27774, name: "Gate City Bank", city: "FARGO", state: "ND", regulator: "OCC", assets: 2774625, holding_company: null },
  { cert: 27806, name: "Fairfield Federal Savings and Loan Association of Lancaster", city: "LANCASTER", state: "OH", regulator: "OCC", assets: 275118, holding_company: null },
  { cert: 27824, name: "Salem Co-operative Bank", city: "SALEM", state: "NH", regulator: "FDIC", assets: 487232, holding_company: null },
  { cert: 27841, name: "Citizens Federal Savings and Loan Association", city: "COVINGTON", state: "KY", regulator: "OCC", assets: 43101, holding_company: null },
  { cert: 27884, name: "Huntington Federal Savings Bank", city: "HUNTINGTON", state: "WV", regulator: "OCC", assets: 553086, holding_company: null },
  { cert: 27897, name: "Black Mountain Savings Bank, SSB", city: "BLACK MOUNTAIN", state: "NC", regulator: "FDIC", assets: 44872, holding_company: null },
  { cert: 27898, name: "Home Savings and Loan Association of Carroll County, F.A.", city: "NORBORNE", state: "MO", regulator: "OCC", assets: 88020, holding_company: null },
  { cert: 27910, name: "Central Savings, f.s.b.", city: "CHICAGO", state: "IL", regulator: "OCC", assets: 117869, holding_company: null },
  { cert: 27943, name: "Brentwood Bank", city: "BETHEL PARK", state: "PA", regulator: "FDIC", assets: 906837, holding_company: "MUTUAL HOLDING COMPANY OF WESTERN PENNSYLVANIA" },
  { cert: 27965, name: "Greenville Federal", city: "GREENVILLE", state: "OH", regulator: "OCC", assets: 212611, holding_company: "GREENVILLE FEDERAL MHC" },
  { cert: 28035, name: "Belmont Savings Bank, SSB", city: "BELMONT", state: "NC", regulator: "FDIC", assets: 109668, holding_company: null },
  { cert: 28060, name: "Citizens Federal Savings and Loan Association", city: "BELLEFONTAINE", state: "OH", regulator: "OCC", assets: 161562, holding_company: null },
  { cert: 28063, name: "The Covington Savings and Loan Association", city: "COVINGTON", state: "OH", regulator: "OCC", assets: 80245, holding_company: "COVINGTON FINANCIAL CORPORATION, MHC" },
  { cert: 28080, name: "The Harrison Building and Loan Association", city: "HARRISON", state: "OH", regulator: "FDIC", assets: 250231, holding_company: null },
  { cert: 28103, name: "Collinsville Building and Loan Association", city: "COLLINSVILLE", state: "IL", regulator: "OCC", assets: 132399, holding_company: null },
  { cert: 28116, name: "Yakima Federal Savings and Loan Association", city: "YAKIMA", state: "WA", regulator: "FDIC", assets: 2019897, holding_company: null },
  { cert: 28155, name: "Profile Bank", city: "ROCHESTER", state: "NH", regulator: "FED", assets: 297675, holding_company: "PROFILE BANCORP MHC" },
  { cert: 28157, name: "The Cincinnatus Savings & Loan Co.", city: "CINCINNATI", state: "OH", regulator: "FDIC", assets: 128699, holding_company: "CINCINNATUS COMMUNITY BANCORP, MHC" },
  { cert: 28167, name: "Eastern Connecticut Savings Bank", city: "NORWICH", state: "CT", regulator: "FED", assets: 270820, holding_company: null },
  { cert: 28186, name: "MCS Bank", city: "MILROY", state: "PA", regulator: "FDIC", assets: 189253, holding_company: null },
  { cert: 28208, name: "San Luis Valley Federal Bank", city: "ALAMOSA", state: "CO", regulator: "OCC", assets: 332596, holding_company: "COLORADO MUTUAL HOLDING COMPANY" },
  { cert: 28213, name: "Winter Hill Bank, FSB", city: "SOMERVILLE", state: "MA", regulator: "OCC", assets: 344965, holding_company: null },
  { cert: 28217, name: "Warsaw Federal Savings and Loan Association", city: "CINCINNATI", state: "OH", regulator: "OCC", assets: 58889, holding_company: "FIRST MUTUAL HOLDING CO." },
  { cert: 28222, name: "Haddon Savings Bank", city: "HADDON HEIGHTS", state: "NJ", regulator: "FDIC", assets: 376834, holding_company: null },
  { cert: 28246, name: "Home Savings Bank", city: "CHANUTE", state: "KS", regulator: "OCC", assets: 78814, holding_company: null },
  { cert: 28266, name: "Raymond Federal Bank", city: "RAYMOND", state: "WA", regulator: "FDIC", assets: 66091, holding_company: null },
  { cert: 28277, name: "Ozarks Federal Savings and Loan Association", city: "FARMINGTON", state: "MO", regulator: "OCC", assets: 257996, holding_company: null },
  { cert: 28288, name: "Auburn Savings Bank, FSB", city: "AUBURN", state: "ME", regulator: "OCC", assets: 90944, holding_company: "AUBURN BANCORP, MHC" },
  { cert: 28302, name: "Mutual Federal Bank", city: "CHICAGO", state: "IL", regulator: "OCC", assets: 88491, holding_company: "MUTUAL FEDERAL BANCORP, MHC" },
  { cert: 28314, name: "Riverside Savings Bank, SSB", city: "ROANOKE RAPIDS", state: "NC", regulator: "FDIC", assets: 95798, holding_company: null },
  { cert: 28315, name: "RG Bank, A Savings and Loan Association", city: "MONTE VISTA", state: "CO", regulator: "FDIC", assets: 140107, holding_company: null },
  { cert: 28316, name: "FIDELITY BANK", city: "NEW ORLEANS", state: "LA", regulator: "FDIC", assets: 1004612, holding_company: null },
  { cert: 28348, name: "Belmont Savings Bank", city: "BELLAIRE", state: "OH", regulator: "FDIC", assets: 419610, holding_company: null },
  { cert: 28368, name: "Middlesex Federal Savings, F.A.", city: "SOMERVILLE", state: "MA", regulator: "OCC", assets: 455591, holding_company: "MIDDLESEX FEDERAL MHC" },
  { cert: 28369, name: "Rockland Savings Bank, FSB", city: "ROCKLAND", state: "ME", regulator: "OCC", assets: 88042, holding_company: null },
  { cert: 28401, name: "Eureka Savings Bank", city: "LA SALLE", state: "IL", regulator: "FDIC", assets: 402961, holding_company: null },
  { cert: 28425, name: "Central Federal Savings and Loan Association", city: "CICERO", state: "IL", regulator: "OCC", assets: 196159, holding_company: null },
  { cert: 28463, name: "Liberty Bank", city: "IRONTON", state: "OH", regulator: "FDIC", assets: 59159, holding_company: "LIBERTY FEDERAL BANCORP, MHC" },
  { cert: 28471, name: "Roxboro Savings Bank, SSB", city: "ROXBORO", state: "NC", regulator: "FDIC", assets: 292760, holding_company: null },
  { cert: 28478, name: "Farmers and Mechanics Federal Savings Bank", city: "BLOOMFIELD", state: "IN", regulator: "FDIC", assets: 121151, holding_company: null },
  { cert: 28480, name: "Columbia Savings and Loan Association", city: "MILWAUKEE", state: "WI", regulator: "FDIC", assets: 24537, holding_company: null },
  { cert: 28481, name: "Colonial Federal Savings Bank", city: "QUINCY", state: "MA", regulator: "OCC", assets: 336043, holding_company: "15 BEACH MHC" },
  { cert: 28507, name: "Argentine Federal Savings", city: "KANSAS CITY", state: "KS", regulator: "OCC", assets: 55742, holding_company: null },
  { cert: 28515, name: "TrustTexas Bank, SSB", city: "CUERO", state: "TX", regulator: "FDIC", assets: 379282, holding_company: "TRUSTTEXAS MUTUAL HOLDING COMPANY" },
  { cert: 28530, name: "Forward Bank", city: "MARSHFIELD", state: "WI", regulator: "FDIC", assets: 935505, holding_company: "FORWARD MUTUAL HOLDING COMPANY" },
  { cert: 28555, name: "Valley Central Bank", city: "LIBERTY TOWNSHIP", state: "OH", regulator: "FDIC", assets: 153786, holding_company: "VALLEY CENTRAL, MHC" },
  { cert: 28585, name: "Maple City Savings Bank, FSB", city: "HORNELL", state: "NY", regulator: "OCC", assets: 92265, holding_company: "MAPLE CITY SAVINGS, MHC" },
  { cert: 28599, name: "Olympia Federal Savings and Loan Association", city: "OLYMPIA", state: "WA", regulator: "FDIC", assets: 914024, holding_company: null },
  { cert: 28611, name: "Pulaski Savings Bank", city: "CHICAGO", state: "IL", regulator: "FDIC", assets: 52631, holding_company: null },
  { cert: 28614, name: "The Equitable Bank, S.S.B.", city: "WAUWATOSA", state: "WI", regulator: "FDIC", assets: 336426, holding_company: "TEB MHC" },
  { cert: 28637, name: "Milton Savings Bank", city: "MILTON", state: "PA", regulator: "OCC", assets: 70660, holding_company: null },
  { cert: 28652, name: "Fairview Savings and Loan Association", city: "FAIRVIEW", state: "OK", regulator: "OCC", assets: 48817, holding_company: null },
  { cert: 28663, name: "The Brookville Building and Savings Association", city: "BROOKVILLE", state: "OH", regulator: "FDIC", assets: 44181, holding_company: null },
  { cert: 28667, name: "Homestead Savings Bank", city: "ALBION", state: "MI", regulator: "OCC", assets: 77986, holding_company: null },
  { cert: 28677, name: "Conneaut Savings Bank", city: "CONNEAUT", state: "OH", regulator: "FDIC", assets: 82582, holding_company: "CONNEAUT BANCORP MHC" },
  { cert: 28679, name: "North Shore Bank", city: "BROOKFIELD", state: "WI", regulator: "FDIC", assets: 2582111, holding_company: null },
  { cert: 28701, name: "Ambler Savings Bank", city: "AMBLER", state: "PA", regulator: "FDIC", assets: 503452, holding_company: null },
  { cert: 28706, name: "First Federal Savings and Loan Association of Greene Co", city: "WAYNESBURG", state: "PA", regulator: "OCC", assets: 998487, holding_company: null },
  { cert: 28708, name: "GSL Savings Bank", city: "GUTTENBERG", state: "NJ", regulator: "FDIC", assets: 128545, holding_company: null },
  { cert: 28712, name: "First Federal Savings of Middletown", city: "MIDDLETOWN", state: "NY", regulator: "OCC", assets: 164011, holding_company: null },
  { cert: 28722, name: "Kentland Federal Savings and Loan Association", city: "KENTLAND", state: "IN", regulator: "OCC", assets: 3670, holding_company: null },
  { cert: 28723, name: "First Savings Bank", city: "DANVILLE", state: "IL", regulator: "FDIC", assets: 34343, holding_company: null },
  { cert: 28729, name: "Ascendia Bank", city: "GLEN ROCK", state: "NJ", regulator: "FDIC", assets: 338458, holding_company: null },
  { cert: 28747, name: "Hoyne Savings Bank", city: "CHICAGO", state: "IL", regulator: "FDIC", assets: 466197, holding_company: "HOYNE SAVINGS, MHC" },
  { cert: 28769, name: "First Federal Savings Bank of Angola", city: "ANGOLA", state: "IN", regulator: "OCC", assets: 140605, holding_company: null },
  { cert: 28778, name: "Somerset Savings Bank, SLA", city: "BOUND BROOK", state: "NJ", regulator: "FDIC", assets: 649630, holding_company: null },
  { cert: 28780, name: "Arundel Federal Savings Bank", city: "GLEN BURNIE", state: "MD", regulator: "OCC", assets: 441492, holding_company: null },
  { cert: 28788, name: "Sturdy Savings Bank", city: "STONE HARBOR", state: "NJ", regulator: "FDIC", assets: 1210083, holding_company: null },
  { cert: 28790, name: "Superior Savings Bank", city: "SUPERIOR", state: "WI", regulator: "FDIC", assets: 81451, holding_company: null },
  { cert: 28793, name: "Sharon Bank", city: "SPRINGFIELD", state: "PA", regulator: "FDIC", assets: 163306, holding_company: "SHARON MUTUAL HOLDING COMPANY" },
  { cert: 28818, name: "Crest Savings Bank", city: "WILDWOOD", state: "NJ", regulator: "FDIC", assets: 597039, holding_company: "CREST SAVINGS BANCORP, MHC" },
  { cert: 28834, name: "Columbia Bank", city: "FAIR LAWN", state: "NJ", regulator: "OCC", assets: 8784587, holding_company: "COLUMBIA BANK MHC" },
  { cert: 28836, name: "United Savings Bank", city: "PHILADELPHIA", state: "PA", regulator: "FDIC", assets: 465342, holding_company: null },
  { cert: 28837, name: "The Brattleboro Savings and Loan Association", city: "BRATTLEBORO", state: "VT", regulator: "FED", assets: 309393, holding_company: null },
  { cert: 28841, name: "Community Savings Bank", city: "CHICAGO", state: "IL", regulator: "FDIC", assets: 430502, holding_company: null },
  { cert: 28845, name: "First Federal Savings Bank of Twin Falls", city: "TWIN FALLS", state: "ID", regulator: "OCC", assets: 972838, holding_company: null },
  { cert: 28859, name: "First Piedmont Federal Savings and Loan Association of Gaffney", city: "GAFFNEY", state: "SC", regulator: "OCC", assets: 485786, holding_company: null },
  { cert: 28860, name: "Century Savings and Loan Association", city: "TRINIDAD", state: "CO", regulator: "FDIC", assets: 90962, holding_company: null },
  { cert: 28870, name: "Wallkill Valley Federal Savings and Loan Association", city: "WALLKILL", state: "NY", regulator: "OCC", assets: 355697, holding_company: "WALLKILL VALLEY BANCORP MHC" },
  { cert: 28894, name: "Security Federal Savings Bank", city: "LOGANSPORT", state: "IN", regulator: "OCC", assets: 322203, holding_company: "SECURITY FEDERAL MUTUAL BANCORP" },
  { cert: 28908, name: "Iron Workers Savings Bank", city: "ASTON", state: "PA", regulator: "FDIC", assets: 213663, holding_company: null },
  { cert: 28914, name: "Evergreen Federal Bank", city: "GRANTS PASS", state: "OR", regulator: "OCC", assets: 579413, holding_company: null },
  { cert: 28924, name: "First Federal Savings Bank", city: "OTTAWA", state: "IL", regulator: "OCC", assets: 374430, holding_company: null },
  { cert: 28925, name: "Security Savings Bank", city: "MONMOUTH", state: "IL", regulator: "FDIC", assets: 254022, holding_company: "SECURITY BANCORP, MHC" },
  { cert: 28942, name: "Carthage Savings and Loan, National Association", city: "CARTHAGE", state: "NY", regulator: "OCC", assets: 277828, holding_company: "RIVERBANK FINANCIAL CORPORATION, MHC" },
  { cert: 28949, name: "Amory Federal Savings and Loan Association", city: "AMORY", state: "MS", regulator: "OCC", assets: 78143, holding_company: null },
  { cert: 28983, name: "Ladysmith Federal Savings and Loan Association", city: "LADYSMITH", state: "WI", regulator: "OCC", assets: 73512, holding_company: null },
  { cert: 29005, name: "First Federal Savings and Loan Association", city: "CENTERBURG", state: "OH", regulator: "OCC", assets: 24244, holding_company: null },
  { cert: 29009, name: "Liberty Bank for Savings", city: "CHICAGO", state: "IL", regulator: "FDIC", assets: 881478, holding_company: null },
  { cert: 29024, name: "Bedford Federal Savings Bank", city: "BEDFORD", state: "IN", regulator: "FDIC", assets: 180715, holding_company: null },
  { cert: 29035, name: "Hancock County Savings Bank, F.S.B.", city: "CHESTER", state: "WV", regulator: "OCC", assets: 410752, holding_company: null },
  { cert: 29047, name: "First Federal Bank of Kansas City", city: "LEES SUMMIT", state: "MO", regulator: "FDIC", assets: 934949, holding_company: null },
  { cert: 29049, name: "Lake City Federal Bank", city: "LAKE CITY", state: "MN", regulator: "OCC", assets: 79473, holding_company: null },
  { cert: 29059, name: "Tucumcari Federal Savings and Loan Association", city: "TUCUMCARI", state: "NM", regulator: "OCC", assets: 35512, holding_company: null },
  { cert: 29061, name: "Tarboro Savings Bank, SSB", city: "TARBORO", state: "NC", regulator: "FDIC", assets: 52517, holding_company: null },
  { cert: 29065, name: "Elberton Federal Savings and Loan Association", city: "ELBERTON", state: "GA", regulator: "OCC", assets: 26975, holding_company: null },
  { cert: 29066, name: "Del Norte Bank", city: "DEL NORTE", state: "CO", regulator: "FDIC", assets: 124440, holding_company: "DEL NORTE M.H.C." },
  { cert: 29090, name: "First Federal Savings and Loan Association", city: "NEWARK", state: "OH", regulator: "OCC", assets: 235052, holding_company: null },
  { cert: 29121, name: "Union Savings Bank", city: "FREEPORT", state: "IL", regulator: "FDIC", assets: 191921, holding_company: "UNION BANCSHARES, MHC" },
  { cert: 29135, name: "First Federal Savings and Loan Association of Van Wert", city: "VAN WERT", state: "OH", regulator: "OCC", assets: 126486, holding_company: "FIRST FEDERAL SAVINGS & LOAN ASSOCIATION OF VAN WERT, MHC" },
  { cert: 29164, name: "First Federal Savings and Loan Association of Valdosta", city: "VALDOSTA", state: "GA", regulator: "OCC", assets: 212168, holding_company: null },
  { cert: 29170, name: "United Roosevelt Savings Bank", city: "CARTERET", state: "NJ", regulator: "FDIC", assets: 250381, holding_company: "UNITED ROOSEVELT MHC" },
  { cert: 29173, name: "New Carlisle Federal Savings Bank", city: "NEW CARLISLE", state: "OH", regulator: "OCC", assets: 160511, holding_company: null },
  { cert: 29186, name: "Lawrenceburg Federal Bank", city: "LAWRENCEBURG", state: "TN", regulator: "FDIC", assets: 75053, holding_company: null },
  { cert: 29188, name: "Fox Valley Savings Bank", city: "FOND DU LAC", state: "WI", regulator: "FDIC", assets: 394538, holding_company: "FVSB MUTUAL BANCORP, MHC" },
  { cert: 29208, name: "Dalhart Federal Savings & Loan Association, SSB", city: "DALHART", state: "TX", regulator: "FDIC", assets: 210690, holding_company: "DALHART FEDERAL MUTUAL HOLDING COMPANY" },
  { cert: 29227, name: "Washington Savings Bank", city: "EFFINGHAM", state: "IL", regulator: "FDIC", assets: 588997, holding_company: "WASHINGTON SAVINGS MHC" },
  { cert: 29231, name: "County Savings Bank", city: "ESSINGTON", state: "PA", regulator: "OCC", assets: 89740, holding_company: null },
  { cert: 29238, name: "Woodruff Federal Savings and Loan Association", city: "WOODRUFF", state: "SC", regulator: "OCC", assets: 103831, holding_company: null },
  { cert: 29241, name: "Henderson Federal Savings Bank", city: "HENDERSON", state: "TX", regulator: "OCC", assets: 111591, holding_company: null },
  { cert: 29293, name: "Cumberland Federal Bank, FSB", city: "CUMBERLAND", state: "WI", regulator: "OCC", assets: 187329, holding_company: null },
  { cert: 29294, name: "Prevail Bank", city: "MEDFORD", state: "WI", regulator: "OCC", assets: 860665, holding_company: "PREVAIL MUTUAL HOLDINGS INC." },
  { cert: 29345, name: "First Federal Savings and Loan Association", city: "DELTA", state: "OH", regulator: "OCC", assets: 199910, holding_company: "FIRST FEDDELTA BANCSHARES, MHC" },
  { cert: 29357, name: "Family Bank", city: "PELHAM", state: "GA", regulator: "OCC", assets: 126904, holding_company: null },
  { cert: 29384, name: "Peru Federal Savings Bank", city: "PERU", state: "IL", regulator: "OCC", assets: 171848, holding_company: null },
  { cert: 29426, name: "Worthington Federal Savings Bank, FSB", city: "WORTHINGTON", state: "MN", regulator: "OCC", assets: 90320, holding_company: null },
  { cert: 29430, name: "Compass Savings Bank", city: "WILMERDING", state: "PA", regulator: "FDIC", assets: 58319, holding_company: null },
  { cert: 29449, name: "North Side Federal Savings and Loan Association of Chicago", city: "CHICAGO", state: "IL", regulator: "OCC", assets: 49492, holding_company: null },
  { cert: 29471, name: "Armstrong County Building and Loan Association", city: "FORD CITY", state: "PA", regulator: "FDIC", assets: 93342, holding_company: null },
  { cert: 29476, name: "Home Federal Savings and Loan Association of Grand Island", city: "GRAND ISLAND", state: "NE", regulator: "OCC", assets: 349477, holding_company: null },
  { cert: 29486, name: "Kingstree Federal Savings and Loan Association", city: "KINGSTREE", state: "SC", regulator: "OCC", assets: 39835, holding_company: "KINGSTREE BANCSHARES, M.H.C." },
  { cert: 29488, name: "First Federal Savings and Loan Association of Lakewood", city: "LAKEWOOD", state: "OH", regulator: "OCC", assets: 2207305, holding_company: "FIRST MUTUAL HOLDING CO." },
  { cert: 29490, name: "First Federal Savings & Loan Association of Ravenswood", city: "RAVENSWOOD", state: "WV", regulator: "OCC", assets: 25830, holding_company: null },
  { cert: 29496, name: "Seneca Savings", city: "BALDWINSVILLE", state: "NY", regulator: "OCC", assets: 222608, holding_company: "SENECA FINANCIAL MHC" },
  { cert: 29501, name: "Interstate Federal Savings and Loan Association of McGregor", city: "MCGREGOR", state: "IA", regulator: "OCC", assets: 7992, holding_company: null },
  { cert: 29517, name: "Pioneer Federal Savings and Loan Association", city: "DILLON", state: "MT", regulator: "FDIC", assets: 103385, holding_company: null },
  { cert: 29520, name: "Washington Financial Bank", city: "WASHINGTON", state: "PA", regulator: "FDIC", assets: 1654591, holding_company: "WFSB MUTUAL HOLDING COMPANY" },
  { cert: 29521, name: "Fidelity Federal Savings and Loan Association of Delaware", city: "DELAWARE", state: "OH", regulator: "OCC", assets: 121499, holding_company: "FIDELITY FEDERAL SAVINGS & LOAN ASSOCIATION, MHC" },
  { cert: 29532, name: "Nokomis Savings Bank", city: "NOKOMIS", state: "IL", regulator: "FDIC", assets: 28389, holding_company: null },
  { cert: 29535, name: "De Witt Savings Bank", city: "CLINTON", state: "IL", regulator: "FDIC", assets: 143749, holding_company: null },
  { cert: 29537, name: "First Federal Bank & Trust", city: "SHERIDAN", state: "WY", regulator: "OCC", assets: 385054, holding_company: null },
  { cert: 29571, name: "The Home Savings and Loan Company of Kenton, Ohio", city: "KENTON", state: "OH", regulator: "FDIC", assets: 183227, holding_company: null },
  { cert: 29578, name: "Monroe Federal Savings and Loan Association", city: "TIPP CITY", state: "OH", regulator: "OCC", assets: 127436, holding_company: null },
  { cert: 29582, name: "Pee Dee Federal Savings Bank", city: "MARION", state: "SC", regulator: "OCC", assets: 35171, holding_company: null },
  { cert: 29613, name: "Rosedale Federal Savings and Loan Association", city: "NOTTINGHAM", state: "MD", regulator: "OCC", assets: 1021460, holding_company: null },
  { cert: 29617, name: "First Mutual Bank, FSB", city: "BELPRE", state: "OH", regulator: "OCC", assets: 93477, holding_company: "FIRST MUTUAL HOLDING CO." },
  { cert: 29624, name: "First Federal Savings and Loan Association of McMinnville", city: "MCMINNVILLE", state: "OR", regulator: "OCC", assets: 548435, holding_company: null },
  { cert: 29627, name: "Second Federal Savings and Loan Association of Philadelphia", city: "PHILADELPHIA", state: "PA", regulator: "OCC", assets: 23028, holding_company: null },
  { cert: 29632, name: "Windsor Federal Savings and Loan Association", city: "WINDSOR", state: "CT", regulator: "OCC", assets: 655774, holding_company: "WINDSOR FEDERAL, MHC" },
  { cert: 29636, name: "First Federal Savings and Loan Association of Bath", city: "BATH", state: "ME", regulator: "OCC", assets: 160366, holding_company: null },
  { cert: 29637, name: "Big Horn Federal Savings Bank", city: "GREYBULL", state: "WY", regulator: "OCC", assets: 315500, holding_company: null },
  { cert: 29645, name: "First Federal Savings and Loan Association of Central Illinois, S.B.", city: "SHELBYVILLE", state: "IL", regulator: "FDIC", assets: 194112, holding_company: null },
  { cert: 29646, name: "First Federal Savings and Loan Association", city: "ABERDEEN", state: "MS", regulator: "OCC", assets: 46224, holding_company: null },
  { cert: 29657, name: "Great Midwest Bank, S.S.B.", city: "BROOKFIELD", state: "WI", regulator: "FDIC", assets: 908733, holding_company: null },
  { cert: 29672, name: "cfsbank", city: "CHARLEROI", state: "PA", regulator: "OCC", assets: 505529, holding_company: "CHARLEROI FINANCIAL MHC" },
  { cert: 29676, name: "Paper City Savings Association", city: "WISCONSIN RAPIDS", state: "WI", regulator: "FDIC", assets: 196989, holding_company: null },
  { cert: 29677, name: "Nashville Savings Bank", city: "NASHVILLE", state: "IL", regulator: "FDIC", assets: 86053, holding_company: null },
  { cert: 29683, name: "Home Federal Bank of Tennessee", city: "KNOXVILLE", state: "TN", regulator: "OCC", assets: 2541489, holding_company: null },
  { cert: 29685, name: "Martinsville First Savings Bank", city: "MARTINSVILLE", state: "VA", regulator: "OCC", assets: 38898, holding_company: "FIRST MUTUAL HOLDING CO." },
  { cert: 29691, name: "KeySavings Bank", city: "WISCONSIN RAPIDS", state: "WI", regulator: "FDIC", assets: 86387, holding_company: null },
  { cert: 29692, name: "Lincoln FSB of Nebraska", city: "LINCOLN", state: "NE", regulator: "OCC", assets: 308536, holding_company: "LINCOLN FEDERAL BANCORP, M.H.C." },
  { cert: 29710, name: "First Federal Savings Bank of Washington", city: "WASHINGTON", state: "IN", regulator: "FDIC", assets: 75295, holding_company: null },
  { cert: 29743, name: "Aroostook County Federal Savings and Loan Association", city: "CARIBOU", state: "ME", regulator: "OCC", assets: 161670, holding_company: null },
  { cert: 29745, name: "Marathon Bank", city: "WAUSAU", state: "WI", regulator: "FDIC", assets: 236600, holding_company: "MARATHON MHC" },
  { cert: 29749, name: "Southern Hills Community Bank", city: "LEESBURG", state: "OH", regulator: "OCC", assets: 172163, holding_company: null },
  { cert: 29772, name: "Vidalia Federal Savings Bank", city: "VIDALIA", state: "GA", regulator: "OCC", assets: 205795, holding_company: null },
  { cert: 29774, name: "Carrollton Federal Bank", city: "CARROLLTON", state: "KY", regulator: "OCC", assets: 34703, holding_company: null },
  { cert: 29800, name: "Lisle Savings Bank", city: "LISLE", state: "IL", regulator: "FDIC", assets: 580200, holding_company: null },
  { cert: 29809, name: "First Savings Bank of Hegewisch", city: "CHICAGO", state: "IL", regulator: "FDIC", assets: 812420, holding_company: null },
  { cert: 29813, name: "Peoples Savings and Loan Company", city: "BUCYRUS", state: "OH", regulator: "FDIC", assets: 151706, holding_company: null },
  { cert: 29835, name: "Milford Federal Bank", city: "MILFORD", state: "MA", regulator: "OCC", assets: 438696, holding_company: null },
  { cert: 29838, name: "First Federal Savings and Loan Association of Lorain", city: "LORAIN", state: "OH", regulator: "OCC", assets: 467865, holding_company: null },
  { cert: 29842, name: "Commonwealth Co-operative Bank", city: "HYDE PARK", state: "MA", regulator: "FED", assets: 207975, holding_company: null },
  { cert: 29846, name: "Eaton Community Bank", city: "CHARLOTTE", state: "MI", regulator: "OCC", assets: 426419, holding_company: "EATON FEDERAL MUTUAL HOLDING COMPANY" },
  { cert: 29857, name: "The Liberty Savings Association, FSA", city: "FORT SCOTT", state: "KS", regulator: "OCC", assets: 30770, holding_company: null },
  { cert: 29874, name: "Dearborn Federal Savings Bank", city: "DEARBORN", state: "MI", regulator: "OCC", assets: 269776, holding_company: null },
  { cert: 29875, name: "NVE Bank", city: "ENGLEWOOD", state: "NJ", regulator: "FDIC", assets: 700384, holding_company: "NVE BANCORP, MHC" },
  { cert: 29881, name: "Home Bank SB", city: "MARTINSVILLE", state: "IN", regulator: "OCC", assets: 368772, holding_company: null },
  { cert: 29904, name: "Elizabethton Federal Savings Bank", city: "ELIZABETHTON", state: "TN", regulator: "OCC", assets: 309592, holding_company: null },
  { cert: 29910, name: "Scottsburg Building and Loan Association", city: "SCOTTSBURG", state: "IN", regulator: "FDIC", assets: 78185, holding_company: "SCOTTSBURG B&L, MHC" },
  { cert: 29933, name: "Union Savings and Loan Association", city: "CONNERSVILLE", state: "IN", regulator: "OCC", assets: 180918, holding_company: null },
  { cert: 29937, name: "First Federal Savings Bank of Kentucky", city: "FRANKFORT", state: "KY", regulator: "OCC", assets: 243661, holding_company: "FIRST FEDERAL MHC" },
  { cert: 29941, name: "Bogota Savings Bank", city: "TEANECK", state: "NJ", regulator: "FDIC", assets: 951277, holding_company: "BOGOTA FINANCIAL, MHC" },
  { cert: 29966, name: "The Equitable Savings and Loan Company", city: "CADIZ", state: "OH", regulator: "FDIC", assets: 11213, holding_company: null },
  { cert: 29975, name: "The Peoples Savings Bank", city: "URBANA", state: "OH", regulator: "FDIC", assets: 147491, holding_company: null },
  { cert: 29986, name: "Guardian Savings Bank", city: "GRANITE CITY", state: "IL", regulator: "FDIC", assets: 34814, holding_company: null },
  { cert: 29988, name: "Mutual Savings Association", city: "LEAVENWORTH", state: "KS", regulator: "FDIC", assets: 327504, holding_company: null },
  { cert: 29995, name: "Phoenixville Federal Bank and Trust", city: "PHOENIXVILLE", state: "PA", regulator: "FDIC", assets: 602280, holding_company: null },
  { cert: 29999, name: "Mutual Savings Bank", city: "HARTSVILLE", state: "SC", regulator: "OCC", assets: 52897, holding_company: null },
  { cert: 30012, name: "Third Federal Savings and Loan Association of Cleveland", city: "CLEVELAND", state: "OH", regulator: "OCC", assets: 14549040, holding_company: "THIRD FEDERAL SAVINGS AND LOAN OF CLEVELAND, MHC" },
  { cert: 30031, name: "Huntingdon Savings Bank", city: "HUNTINGDON", state: "PA", regulator: "FDIC", assets: 15823, holding_company: null },
  { cert: 30039, name: "Haven Savings Bank", city: "HOBOKEN", state: "NJ", regulator: "FDIC", assets: 1092301, holding_company: "HAVEN BANCORP, MHC" },
  { cert: 30043, name: "Beardstown Savings s.b.", city: "BEARDSTOWN", state: "IL", regulator: "FDIC", assets: 63851, holding_company: null },
  { cert: 30058, name: "First Federal Savings and Loan Association of Greensburg", city: "GREENSBURG", state: "IN", regulator: "OCC", assets: 161140, holding_company: null },
  { cert: 30065, name: "Peoples Community Bank SB of Monticello, Indiana", city: "MONTICELLO", state: "IN", regulator: "FDIC", assets: 34385, holding_company: null },
  { cert: 30072, name: "Schuyler Savings Bank", city: "KEARNY", state: "NJ", regulator: "FDIC", assets: 128944, holding_company: null },
  { cert: 30076, name: "Spencer Savings Bank, SLA", city: "ELMWOOD PARK", state: "NJ", regulator: "FDIC", assets: 3784556, holding_company: null },
  { cert: 30084, name: "Mercer Savings Bank", city: "CELINA", state: "OH", regulator: "FDIC", assets: 146987, holding_company: null },
  { cert: 30103, name: "Monroe Savings Bank", city: "WILLIAMSTOWN", state: "NJ", regulator: "FDIC", assets: 101588, holding_company: null },
  { cert: 30111, name: "Oconee Federal Savings and Loan Association", city: "SENECA", state: "SC", regulator: "OCC", assets: 526324, holding_company: "OCONEE FEDERAL, MHC" },
  { cert: 30117, name: "Reliance Savings Bank", city: "ALTOONA", state: "PA", regulator: "FDIC", assets: 621206, holding_company: "RELIANCE BANCORP,MHC" },
  { cert: 30119, name: "PennCrest Bank", city: "ALTOONA", state: "PA", regulator: "FDIC", assets: 221830, holding_company: null },
  { cert: 30121, name: "Investment Savings Bank", city: "ALTOONA", state: "PA", regulator: "FDIC", assets: 107687, holding_company: null },
  { cert: 30128, name: "Boonville Federal Savings Bank", city: "BOONVILLE", state: "IN", regulator: "FDIC", assets: 62631, holding_company: null },
  { cert: 30150, name: "Citizens Federal Savings Bank", city: "LEAVENWORTH", state: "KS", regulator: "OCC", assets: 185784, holding_company: null },
  { cert: 30152, name: "Milford Building and Loan Association", city: "MILFORD", state: "IL", regulator: "FDIC", assets: 30012, holding_company: null },
  { cert: 30154, name: "Sewickley Savings Bank", city: "SEWICKLEY", state: "PA", regulator: "FDIC", assets: 285811, holding_company: null },
  { cert: 30155, name: "Hatboro Federal Savings, FA", city: "HATBORO", state: "PA", regulator: "OCC", assets: 562330, holding_company: null },
  { cert: 30176, name: "Home Savings Bank of Wapakoneta", city: "WAPAKONETA", state: "OH", regulator: "FDIC", assets: 39360, holding_company: null },
  { cert: 30183, name: "Millville Savings Bank", city: "MILLVILLE", state: "NJ", regulator: "FDIC", assets: 159056, holding_company: null },
  { cert: 30260, name: "Cross County Savings Bank", city: "MIDDLE VILLAGE", state: "NY", regulator: "FDIC", assets: 539043, holding_company: null },
  { cert: 30270, name: "Citizens Savings Bank", city: "BOGALUSA", state: "LA", regulator: "FDIC", assets: 278738, holding_company: null },
  { cert: 30303, name: "Maspeth Federal Savings and Loan Association", city: "MASPETH", state: "NY", regulator: "OCC", assets: 2051715, holding_company: null },
  { cert: 30313, name: "East Wisconsin Savings Bank", city: "KAUKAUNA", state: "WI", regulator: "FDIC", assets: 271685, holding_company: "WISCONSIN MUTUAL BANCORP, MHC" },
  { cert: 30315, name: "First Federal Savings Bank of Lincolnton", city: "LINCOLNTON", state: "NC", regulator: "OCC", assets: 426587, holding_company: null },
  { cert: 30332, name: "Abbeville Building & Loan (A State-Chartered Savings Bank)", city: "ABBEVILLE", state: "LA", regulator: "FDIC", assets: 58961, holding_company: null },
  { cert: 30350, name: "The Bank of Bennington", city: "BENNINGTON", state: "VT", regulator: "OCC", assets: 494946, holding_company: "COMMUNITY FINANCIAL, MHC" },
  { cert: 30357, name: "Streator Home Savings Bank", city: "STREATOR", state: "IL", regulator: "FDIC", assets: 166716, holding_company: null },
  { cert: 30358, name: "First Savings and Loan Association", city: "MEBANE", state: "NC", regulator: "OCC", assets: 58184, holding_company: null },
  { cert: 30367, name: "1st Bank of Sea Isle City", city: "SEA ISLE CITY", state: "NJ", regulator: "FDIC", assets: 331161, holding_company: "SEA ISLE FINANCIAL CORP, MHC" },
  { cert: 30388, name: "Gunnison Savings and Loan Association", city: "GUNNISON", state: "CO", regulator: "FDIC", assets: 108280, holding_company: null },
  { cert: 30395, name: "Tecumseh Federal Bank", city: "TECUMSEH", state: "NE", regulator: "OCC", assets: 48746, holding_company: null },
  { cert: 30397, name: "Geddes Federal Savings and Loan Association", city: "SYRACUSE", state: "NY", regulator: "OCC", assets: 587587, holding_company: null },
  { cert: 30401, name: "Penn Community Bank", city: "DOYLESTOWN", state: "PA", regulator: "FDIC", assets: 2660709, holding_company: "PENN COMMUNITY MUTUAL HOLDINGS INC" },
  { cert: 30402, name: "Franklin Bank", city: "PILESGROVE", state: "NJ", regulator: "FDIC", assets: 332383, holding_company: null },
  { cert: 30428, name: "Century Savings Bank", city: "VINELAND", state: "NJ", regulator: "FDIC", assets: 627019, holding_company: "CENTURY BANCORP MHC" },
  { cert: 30429, name: "Massena Savings and Loan", city: "MASSENA", state: "NY", regulator: "OCC", assets: 178739, holding_company: null },
  { cert: 30431, name: "SSB Bank", city: "PITTSBURGH", state: "PA", regulator: "FDIC", assets: 251122, holding_company: "SSB BANCORP, MHC" },
  { cert: 30434, name: "Morganton Savings Bank, S.S.B.", city: "MORGANTON", state: "NC", regulator: "FDIC", assets: 121301, holding_company: null },
  { cert: 30441, name: "First Federal Bank of Louisiana", city: "LAKE CHARLES", state: "LA", regulator: "OCC", assets: 1165864, holding_company: null },
  { cert: 30447, name: "Rayne Building and Loan Association", city: "RAYNE", state: "LA", regulator: "FDIC", assets: 57302, holding_company: null },
  { cert: 30470, name: "Manasquan Bank", city: "MANASQUAN", state: "NJ", regulator: "FDIC", assets: 2778051, holding_company: "MB MUTUAL HOLDING COMPANY" },
  { cert: 30492, name: "Jackson Federal Savings and Loan Association", city: "JACKSON", state: "MN", regulator: "OCC", assets: 41016, holding_company: "JACKSON FINANCIAL, MHC" },
  { cert: 30516, name: "Crossbridge Community Bank", city: "TOMAHAWK", state: "WI", regulator: "FDIC", assets: 199267, holding_company: "TCB MUTUAL HOLDING COMPANY" },
  { cert: 30519, name: "Freehold Bank", city: "FREEHOLD", state: "NJ", regulator: "OCC", assets: 293064, holding_company: "COLUMBIA BANK MHC" },
  { cert: 30530, name: "Lake Shore Savings Bank", city: "DUNKIRK", state: "NY", regulator: "OCC", assets: 686391, holding_company: "LAKE SHORE, MHC" },
  { cert: 30544, name: "Marquette Savings Bank", city: "ERIE", state: "PA", regulator: "FDIC", assets: 1126810, holding_company: null },
  { cert: 30551, name: "Westmoreland Federal Savings and Loan Association", city: "LATROBE", state: "PA", regulator: "OCC", assets: 171873, holding_company: null },
  { cert: 30585, name: "Mayville Savings Bank", city: "MAYVILLE", state: "WI", regulator: "FDIC", assets: 74934, holding_company: null },
  { cert: 30619, name: "Abbeville First Bank, SSB", city: "ABBEVILLE", state: "SC", regulator: "FDIC", assets: 117074, holding_company: null },
  { cert: 30637, name: "Greenville Savings Bank", city: "GREENVILLE", state: "PA", regulator: "FDIC", assets: 317862, holding_company: null },
  { cert: 30656, name: "North County Savings Bank", city: "RED BUD", state: "IL", regulator: "FDIC", assets: 65541, holding_company: null },
  { cert: 30680, name: "First Shore Federal Savings and Loan Association", city: "SALISBURY", state: "MD", regulator: "OCC", assets: 327969, holding_company: null },
  { cert: 30688, name: "Peoples First Savings Bank", city: "MASON", state: "OH", regulator: "FDIC", assets: 87898, holding_company: null },
  { cert: 30812, name: "First Federal Savings and Loan Association", city: "PASCAGOULA", state: "MS", regulator: "OCC", assets: 332972, holding_company: null },
  { cert: 30819, name: "Community Partners Savings Bank", city: "SALEM", state: "IL", regulator: "FDIC", assets: 238339, holding_company: null },
  { cert: 30878, name: "Bar Harbor Savings and Loan Association", city: "BAR HARBOR", state: "ME", regulator: "FDIC", assets: 101068, holding_company: null },
  { cert: 30889, name: "The Peoples Savings and Loan Company", city: "WEST LIBERTY", state: "OH", regulator: "FDIC", assets: 93220, holding_company: null },
  { cert: 30969, name: "First FSB of Mascoutah", city: "MASCOUTAH", state: "IL", regulator: "FED", assets: 167609, holding_company: null },
  { cert: 30976, name: "Gouverneur Savings and Loan Association", city: "GOUVERNEUR", state: "NY", regulator: "FDIC", assets: 204971, holding_company: "CAMBRAY MUTUAL HOLDING COMPANY" },
  { cert: 30987, name: "Spratt Savings Bank", city: "CHESTER", state: "SC", regulator: "FDIC", assets: 153881, holding_company: null },
  { cert: 31083, name: "Jarrettsville Federal Savings and Loan Association", city: "JARRETTSVILLE", state: "MD", regulator: "OCC", assets: 127436, holding_company: null },
  { cert: 31090, name: "Blue Grass Federal Savings and Loan Association", city: "PARIS", state: "KY", regulator: "OCC", assets: 35200, holding_company: "FIRST MUTUAL HOLDING CO." },
  { cert: 31184, name: "Citizens Savings Bank", city: "CLARKS SUMMIT", state: "PA", regulator: "OCC", assets: 364936, holding_company: null },
  { cert: 31197, name: "First Federal Savings and Loan Association", city: "HAZARD", state: "KY", regulator: "OCC", assets: 90339, holding_company: "FIRST FEDERAL MHC" },
  { cert: 31198, name: "Greeneville Federal Bank, FSB", city: "GREENEVILLE", state: "TN", regulator: "OCC", assets: 156421, holding_company: null },
  { cert: 31217, name: "LifeStore Bank", city: "WEST JEFFERSON", state: "NC", regulator: "FED", assets: 420575, holding_company: "ASHECO MHC, INC." },
  { cert: 31232, name: "Highland Federal Savings and Loan Association", city: "CROSSVILLE", state: "TN", regulator: "OCC", assets: 66604, holding_company: null },
  { cert: 31266, name: "Jackson Savings Bank, SSB", city: "SYLVA", state: "NC", regulator: "FDIC", assets: 32044, holding_company: null },
  { cert: 31267, name: "Homewood Federal Savings Bank", city: "BALTIMORE", state: "MD", regulator: "OCC", assets: 60867, holding_company: null },
  { cert: 31313, name: "First Federal Bank", city: "LAKE CITY", state: "FL", regulator: "OCC", assets: 3058446, holding_company: "FIRST FEDERAL BANCORP, MHC" },
  { cert: 31329, name: "West Plains Savings and Loan Association", city: "WEST PLAINS", state: "MO", regulator: "FDIC", assets: 92179, holding_company: null },
  { cert: 31345, name: "Hertford Savings Bank, SSB", city: "HERTFORD", state: "NC", regulator: "FDIC", assets: 15227, holding_company: null },
  { cert: 31406, name: "First Federal Savings and Loan Association of San Rafael", city: "SAN RAFAEL", state: "CA", regulator: "OCC", assets: 222524, holding_company: null },
  { cert: 31409, name: "First Federal Savings and Loan Association", city: "MOREHEAD", state: "KY", regulator: "OCC", assets: 34520, holding_company: null },
  { cert: 31410, name: "1st Federal Savings Bank of SC, Inc.", city: "WALTERBORO", state: "SC", regulator: "FDIC", assets: 143309, holding_company: "FIRST CAROLINA BANCSHARES, M.H.C." },
  { cert: 31539, name: "The Wilmington Savings Bank", city: "WILMINGTON", state: "OH", regulator: "FDIC", assets: 203025, holding_company: null },
  { cert: 31694, name: "Volunteer Federal Savings Bank", city: "MADISONVILLE", state: "TN", regulator: "FDIC", assets: 322477, holding_company: null },
  { cert: 31723, name: "Home Savings Bank, FSB", city: "LUDLOW", state: "KY", regulator: "OCC", assets: 25990, holding_company: null },
  { cert: 31774, name: "Home Federal Savings and Loan Association", city: "BAMBERG", state: "SC", regulator: "OCC", assets: 41224, holding_company: null },
  { cert: 31900, name: "CBL State Savings Bank", city: "GREER", state: "SC", regulator: "FDIC", assets: 142999, holding_company: "CITIZENS BUILDING AND LOAN MHC" },
  { cert: 31994, name: "Slovenian Savings and Loan Association of Franklin-Conemaugh", city: "CONEMAUGH", state: "PA", regulator: "OCC", assets: 159240, holding_company: null },
  { cert: 32245, name: "Dollar Bank, Federal Savings Bank", city: "PITTSBURGH", state: "PA", regulator: "OCC", assets: 9926432, holding_company: "DOLLAR MUTUAL BANCORP" },
  { cert: 32286, name: "Community Savings Bank", city: "BETHEL", state: "OH", regulator: "FDIC", assets: 87221, holding_company: null },
  { cert: 32293, name: "Miami Savings Bank", city: "MIAMITOWN", state: "OH", regulator: "FDIC", assets: 139225, holding_company: null },
  { cert: 32306, name: "New Foundation Savings Bank", city: "CINCINNATI", state: "OH", regulator: "FDIC", assets: 25850, holding_company: null },
  { cert: 32307, name: "Galion Building and Loan Bank", city: "GALION", state: "OH", regulator: "FDIC", assets: 74748, holding_company: null },
  { cert: 32348, name: "Taylorsville Savings Bank, SSB", city: "TAYLORSVILLE", state: "NC", regulator: "FDIC", assets: 137523, holding_company: null },
  { cert: 32527, name: "BayVanguard Bank", city: "BALTIMORE", state: "MD", regulator: "FDIC", assets: 836968, holding_company: "BAY-VANGUARD, MHC" },
  { cert: 33645, name: "Lee Bank", city: "LEE", state: "MA", regulator: "FDIC", assets: 529900, holding_company: "BERKSHIRE FINANCIAL SERVICES, INC." },
  { cert: 33802, name: "Tioga-Franklin Savings Bank", city: "PHILADELPHIA", state: "PA", regulator: "FDIC", assets: 66257, holding_company: null },
  { cert: 34058, name: "Lusitania Savings Bank", city: "NEWARK", state: "NJ", regulator: "FDIC", assets: 383686, holding_company: "LUSITANIA FINANCIAL, MHC" },
  { cert: 34711, name: "Farmers Building and Savings Bank", city: "ROCHESTER", state: "PA", regulator: "FDIC", assets: 122317, holding_company: null },
  { cert: 57710, name: "Greene County Commercial Bank", city: "CATSKILL", state: "NY", regulator: "FDIC", assets: 1120128, holding_company: "GREENE COUNTY BANCORP, MHC" },
  { cert: 57849, name: "Pioneer Commercial Bank", city: "ALBANY", state: "NY", regulator: "FDIC", assets: 453148, holding_company: "PIONEER BANCORP MHC" },
  { cert: 58536, name: "Think Mutual Bank", city: "ROCHESTER", state: "MN", regulator: "OCC", assets: 1972150, holding_company: null },
  { cert: 59289, name: "Walden Mutual Bank", city: "CONCORD", state: "NH", regulator: "FDIC", assets: 22693, holding_company: null },
  { cert: 90140, name: "Adams Community Bank", city: "ADAMS", state: "MA", regulator: "FDIC", assets: 931600, holding_company: "COMMUNITY BANCORP OF THE BERKSHIRES MHC" },
  { cert: 90146, name: "Athol Savings Bank", city: "ATHOL", state: "MA", regulator: "FDIC", assets: 582843, holding_company: null },
  { cert: 90169, name: "Bluestone Bank", city: "RAYNHAM", state: "MA", regulator: "FED", assets: 1398628, holding_company: "BLUESTONE FINANCIAL, MHC" },
  { cert: 90173, name: "East Cambridge Savings Bank", city: "CAMBRIDGE", state: "MA", regulator: "FED", assets: 1609978, holding_company: "1854 BANCORP" },
  { cert: 90175, name: "The Bank of Canton", city: "CANTON", state: "MA", regulator: "FDIC", assets: 831740, holding_company: "PONKAPOAG BANCORP, MHC" },
  { cert: 90181, name: "Clinton Savings Bank", city: "CLINTON", state: "MA", regulator: "FDIC", assets: 693626, holding_company: "CLINTON FINANCIAL SERVICES, MHC" },
  { cert: 90183, name: "Middlesex Savings Bank", city: "NATICK", state: "MA", regulator: "FDIC", assets: 6204550, holding_company: "MIDDLESEX BANCORP MHC" },
  { cert: 90188, name: "Easthampton Savings Bank", city: "EASTHAMPTON", state: "MA", regulator: "FED", assets: 1738869, holding_company: "HOMETOWN FINANCIAL GROUP MHC" },
  { cert: 90190, name: "Martha's Vineyard Bank", city: "EDGARTOWN", state: "MA", regulator: "FED", assets: 1307758, holding_company: "VINEYARD BANCORP MHC" },
  { cert: 90191, name: "Eagle Bank", city: "EVERETT", state: "MA", regulator: "FDIC", assets: 584519, holding_company: null },
  { cert: 90196, name: "BayCoast Bank", city: "SWANSEA", state: "MA", regulator: "FDIC", assets: 2820893, holding_company: "NARRAGANSETT FINANCIAL CORPORATION" },
  { cert: 90203, name: "Cape Ann Savings Bank", city: "GLOUCESTER", state: "MA", regulator: "FDIC", assets: 929925, holding_company: null },
  { cert: 90206, name: "Greenfield Savings Bank", city: "GREENFIELD", state: "MA", regulator: "FDIC", assets: 1078877, holding_company: "GSB, MHC" },
  { cert: 90208, name: "Pentucket  Bank", city: "HAVERHILL", state: "MA", regulator: "FDIC", assets: 945137, holding_company: "PENTUCKET BANK HOLDINGS, MHC" },
  { cert: 90213, name: "PeoplesBank", city: "HOLYOKE", state: "MA", regulator: "FDIC", assets: 3668204, holding_company: "PEOPLESBANCORP, MHC" },
  { cert: 90215, name: "Avidia Bank", city: "HUDSON", state: "MA", regulator: "FDIC", assets: 2485908, holding_company: "ASSABET VALLEY BANCORP" },
  { cert: 90227, name: "The Lowell Five Cent Savings Bank", city: "TEWKSBURY", state: "MA", regulator: "FDIC", assets: 1657767, holding_company: "LOWELL FIVE BANCORP MHC" },
  { cert: 90229, name: "Washington Savings Bank", city: "LOWELL", state: "MA", regulator: "FED", assets: 275933, holding_company: null },
  { cert: 90234, name: "Marblehead Bank", city: "MARBLEHEAD", state: "MA", regulator: "FED", assets: 280576, holding_company: null },
  { cert: 90235, name: "Main Street Bank", city: "MARLBOROUGH", state: "MA", regulator: "FDIC", assets: 1463645, holding_company: "MAIN STREET GROUP BANCSHARES MHC" },
  { cert: 90245, name: "Monson Savings Bank", city: "MONSON", state: "MA", regulator: "FDIC", assets: 631830, holding_company: "MONSON FINANCIAL SERVICES MHC" },
  { cert: 90250, name: "Institution for Savings in Newburyport and Its Vicinity", city: "NEWBURYPORT", state: "MA", regulator: "FDIC", assets: 4869275, holding_company: "1820 BANCORP, MHC" },
  { cert: 90251, name: "Newburyport Five Cents Savings Bank", city: "NEWBURYPORT", state: "MA", regulator: "FDIC", assets: 1537046, holding_company: "NEWBURYPORT FIVE CENTS BANCORP MHC" },
  { cert: 90253, name: "MountainOne Bank", city: "NORTH ADAMS", state: "MA", regulator: "FDIC", assets: 922461, holding_company: "MOUNTAINONE FINANCIAL, MHC" },
  { cert: 90258, name: "North Brookfield Savings Bank", city: "NORTH BROOKFIELD", state: "MA", regulator: "FED", assets: 383177, holding_company: "TRUNORTH BANCORP MHC" },
  { cert: 90259, name: "North Easton Savings Bank", city: "SOUTH EASTON", state: "MA", regulator: "FDIC", assets: 1458969, holding_company: null },
  { cert: 90268, name: "Seamen's Bank", city: "PROVINCETOWN", state: "MA", regulator: "FDIC", assets: 493384, holding_company: null },
  { cert: 90282, name: "Cornerstone Bank", city: "SPENCER", state: "MA", regulator: "FED", assets: 1503914, holding_company: "SSB COMMUNITY BANCORP MHC" },
  { cert: 90290, name: "UniBank for Savings", city: "WHITINSVILLE", state: "MA", regulator: "FDIC", assets: 2501503, holding_company: "UFS BANCORP" },
  { cert: 90291, name: "The Savings Bank", city: "WAKEFIELD", state: "MA", regulator: "FDIC", assets: 718723, holding_company: "WAKEFIELD BANCORP MHC" },
  { cert: 90297, name: "Webster Five Cents Savings Bank", city: "WEBSTER", state: "MA", regulator: "FDIC", assets: 1130141, holding_company: "WEBFIVE MHC" },
  { cert: 90303, name: "South Shore Bank", city: "SOUTH WEYMOUTH", state: "MA", regulator: "FED", assets: 2111040, holding_company: "SOUTH SHORE BANCORP MHC" },
  { cert: 90308, name: "Winchester Savings Bank", city: "WINCHESTER", state: "MA", regulator: "FDIC", assets: 685436, holding_company: null },
  { cert: 90311, name: "Bay State Savings Bank", city: "WORCESTER", state: "MA", regulator: "FDIC", assets: 500594, holding_company: "1895 MHC" },
];
